### ISSUE TITLE
Prompt to put detached HEAD on branch suggests incorrect branch.

### ISSUE THREAD

**Issue by devinrhode2** [ivanhofer/git-assistant#4]
I love this extension! It's remarkable! Solves most problems with submodules!
...But it's not perfect, yet!

I was wondering how this extension decides which branch to suggest setting submodules to.

In my .gitmodules file, I specify a branch for all submodules. git-assistant will create little popups asking me if I want a submodule to be on a certain branch. For 2 submodules it was correct, for other submodules, it was asking if I want to checkout a totally different branch. In my .gitmodules, most submodules have a branch, say, `diddy-kong`. These submodule repos have branches like `diddy-kong-port` that were more recently updated than `diddy-kong`. However, the repository has never ever used `diddy-kong-port` in any way. Another project has, but not this git repo. Not this folder. `diddy-kong-port` has never touched this git repo in any way you could imagine. But `diddy-kong-port` may be more updated or the most recently pushed to.

This extension should read the branch from .gitmodules file and enforce that submodules are on and stay on that branch. There are some git hooks that could be used in some way.

**Comment by ivanhofer** [comment]
Thanks, that's nice to hear :)

In your main-repository only a refercence to the last checked out commit of your submodule is stored.
Whenever you make a commit to that submodule, you also have to make a commit in your main-repository to update the reference.
When another person opens the main-repository in VS Code, the extension will see that the references have changed and will call "git submodule update --init" to get all the latest information for the submodules.
All submodules that were updated will get a detached HEAD referencing to the specific commit ID of the last commit of your submodule in your main-repository (in the VS Code SCM-view you see the ID instead of the branchname). The extension looks at all branches of the submodule and picks the branch that has the same commit ID as the reference in the main-repository.
So if the extension checks out the wrong branch, that means that someone commitet changes from that branch to the main-repository or that these two branches reference to the same commit (= two parallel branches).

Can you pleaese check your commit IDs of the wrong assigned branches and tell me if my assumtions are correct?

**Comment by devinrhode2** [comment]
it is 100% correct that the commit is the HEAD of two branches, so these
would be identical branches

still should use the branch specified in .gitmodules

Maybe if commit does not exist on the specified branch then something is
wrong

**Comment by ivanhofer** [comment]
ok, I'll look for a fix

**Comment by ivanhofer** [comment]
I just released version 1.2.1. Your problem should be fixed

**Comment by ctf0** [comment]
@ivanhofer am still having this issue as well. 

`. gitmodules` specify the branch name for each module ex.
```
[submodule "Modules/Admin"]
    path = Modules/Admin
    url = https://github.com/xxx/modules
    branch = Admin
```

however the ext keep showing notification error of `could not find branch for 'adc6e55'  in Submodule 'Modules/Admin'. You have to checkout the branch manually.`

if u need more info plz ask.

**Comment by devinrhode2** [comment]
Git version and vscode version?

**Comment by devinrhode2** [comment]
Also, if you do a plain 'git checkout Admin' inside the submodule root,
does it work? Or are you required to do git fetch/etc?

**Comment by ctf0** [comment]
git `2.30.0`
vscode 
```
Version: 1.53.0-insider
Commit: ed72c64b87ede96fb51bc16870f9d2ecbf4fcc57
Date: 2021-01-22T17:17:02.999Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

> Also, if you do a plain 'git checkout Admin' inside the submodule root, does it work?

yes

**Comment by ivanhofer** [comment]
Hi @ctf0,

I'm sorry, but I currently have no free time to investigate the problem in detail.
Could you please provide me a demo-repository step-by-step guide on how to reproduce the issue?

**Comment by ctf0** [comment]
@ivanhofer thanks for replying, its okey, no need as i stopped using submodules.

**Comment by ivanhofer** [comment]
Good. Not using git submodules at all is the best option ^^
It saves you from a lot of problems.

**Comment by ctf0** [comment]
it has its advantages but the maintainability is an agony 🥵  🤦
